name: Benchmarks

on:
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install rust-toolchain@1.74.1
        uses: dtolnay/rust-toolchain@1.74.1

        with:
          components: rustfmt, clippy

      # Calculate cache keys
      - name: Set bi-weekly cache key
        run: |
          YEAR=$(date +%Y)
          BIWEEK=$(( ($(date +%U) + 1) / 2 ))
          echo "CACHE_VERSION=${YEAR}(${BIWEEK})" >> $GITHUB_ENV

          # Hash of all files that could affect the build
          HASH=$(echo "${{ hashFiles('**/Cargo.lock', '**/Cargo.toml', '.github/workflows/**') }}")
          echo "BUILD_HASH=${HASH}" >> $GITHUB_ENV
        shell: bash

      # Restore Rust build cache and artifacts
      - name: Restore Rust cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/release/
            target/criterion/
          # Cache key depends on the bi-week we are on (cache version)
          key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-cargo-

      # Run benchmarks
      - name: Run cargo bench
        run: cargo bench

      # Save cache only if the previous steps succeeded and there was not an exact cache key match
      # This happens everytime we modify any `cargo.lock` or `cargo.toml`, or each two weeks (caching recent changes)
      - name: Save Rust cache
        if: success() && steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/release/
            target/criterion/
          key: ${{ steps.cache.outputs.cache-primary-key }}
      # Store benchmark results
      - name: Store benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion
